[build]
  base = "/"

[context.production]
  command = "yarn build"
  publish = "build"
  
[context.branch-deploy]
  publish = "/"
  command = ""
  
[[redirects]]
  from = https://berlm-me.netlify.com/*
  to = https://www.berlm.me/:splat
  status = 301
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200